networks:
  app:

services:
  bot:
    build:
      context: .
    container_name: bot
    env_file:
      - bot/.env
    command: bash -c "cd bot && poetry run alembic upgrade head && cd .. && poetry run python -m bot"
    depends_on:
      - postgres
    networks:
      - app
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file:
      - bot/.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}"
    networks:
      - app


